ncluded:
  - Source
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_body_length
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - compiler_protocol_init
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - control_statement
  - convenience_type
  - cyclomatic_complexity
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_direct_init
  - discouraged_object_literal
  - discouraged_optional_boolean
  - duplicate_enum_cases
  - duplicate_imports
  - dynamic_inline
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - explicit_init
  - explicit_top_level_acl
  - extension_access_modifier
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - literal_expression_end_indentation
  - nimble_operator
  - no_grouping_extension
  - number_separator
  - object_literal
  - opening_brace
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - type_name
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
disabled_rules:
  - force_try
  - no_extension_access_modifier
  - trailing_comma
  - trailing_newline
file_header:
  required_pattern: |
    \/\/
    \/\/  .*?\.swift
    \/\/  iOS Common
    \/\/
    \/\/  Created by .*? on \d{4}-\d{2}-\d{2}\.
    \/\/  Copyright © \d{4} vinicius.io - All rights reserved\.
    \/\/
identifier_name:
  min_length: 3
  excluded:
    - i
    - id